// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

// Generated by tools/model_reference.py; checked-in oracle vectors.
import {Test} from "forge-std/Test.sol";
import {QuantumModel} from "../src/QuantumModel.sol";

contract QuantumVectorsTest is Test {
    function test_referenceVector00() public pure {
        uint32[8] memory p = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(781250), 31250, 31250, 31250, 31250, 31250, 31250, 31250];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector01() public pure {
        uint32[8] memory p = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 1];
        uint32[8] memory expected = [uint32(585938), 23438, 23438, 23438, 23437, 23437, 23437, 273437];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector02() public pure {
        uint32[8] memory p = [uint32(999993), 1, 1, 1, 1, 1, 1, 1];
        uint16[8] memory counts = [uint16(1024), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(344737), 93609, 93609, 93609, 93609, 93609, 93609, 93609];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector03() public pure {
        uint32[8] memory p = [uint32(1), 2, 3, 4, 5, 6, 7, 999972];
        uint16[8] memory counts = [uint16(128), 128, 128, 128, 128, 128, 128, 128];
        uint32[8] memory expected = [uint32(126906), 124752, 124897, 124576, 125165, 124560, 124527, 124617];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector04() public pure {
        uint32[8] memory p = [uint32(1000000), 0, 0, 0, 0, 0, 0, 0];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector05() public pure {
        uint32[8] memory p = [uint32(0), 1000000, 0, 0, 0, 0, 0, 0];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector06() public pure {
        uint32[8] memory p = [uint32(0), 0, 1000000, 0, 0, 0, 0, 0];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector07() public pure {
        uint32[8] memory p = [uint32(0), 0, 0, 1000000, 0, 0, 0, 0];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector08() public pure {
        uint32[8] memory p = [uint32(0), 0, 0, 0, 1000000, 0, 0, 0];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector09() public pure {
        uint32[8] memory p = [uint32(0), 0, 0, 0, 0, 1000000, 0, 0];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector10() public pure {
        uint32[8] memory p = [uint32(0), 0, 0, 0, 0, 0, 1000000, 0];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector11() public pure {
        uint32[8] memory p = [uint32(0), 0, 0, 0, 0, 0, 0, 1000000];
        uint16[8] memory counts = [uint16(0), 0, 0, 0, 0, 0, 0, 0];
        uint32[8] memory expected = [uint32(125000), 125000, 125000, 125000, 125000, 125000, 125000, 125000];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector12() public pure {
        uint32[8] memory p = [uint32(21315), 31988, 256352, 270902, 265907, 67788, 80593, 5155];
        uint16[8] memory counts = [uint16(114), 63, 18, 101, 57, 67, 53, 101];
        uint32[8] memory expected = [uint32(506709), 63302, 36853, 67469, 51665, 71225, 135081, 67696];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector13() public pure {
        uint32[8] memory p = [uint32(174794), 41104, 232607, 11433, 190495, 231997, 106054, 11516];
        uint16[8] memory counts = [uint16(32), 124, 30, 111, 124, 119, 114, 51];
        uint32[8] memory expected = [uint32(495994), 108435, 52851, 75414, 68808, 77896, 78326, 42276];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector14() public pure {
        uint32[8] memory p = [uint32(40658), 168761, 110588, 33779, 264709, 282834, 81488, 17183];
        uint16[8] memory counts = [uint16(128), 111, 49, 91, 69, 58, 14, 53];
        uint32[8] memory expected = [uint32(551547), 72280, 81864, 82863, 61390, 51485, 49571, 49000];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector15() public pure {
        uint32[8] memory p = [uint32(137217), 86852, 172904, 157195, 203769, 144536, 15804, 81723];
        uint16[8] memory counts = [uint16(92), 33, 107, 17, 3, 23, 79, 94];
        uint32[8] memory expected = [uint32(595207), 41856, 88382, 38746, 28970, 38653, 90140, 78046];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector16() public pure {
        uint32[8] memory p = [uint32(244103), 254022, 74329, 99643, 19039, 38623, 84178, 186063];
        uint16[8] memory counts = [uint16(123), 2, 58, 9, 89, 17, 1, 3];
        uint32[8] memory expected = [uint32(616187), 29584, 71488, 31830, 116892, 39025, 68901, 26093];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector17() public pure {
        uint32[8] memory p = [uint32(164275), 125913, 58271, 22081, 126461, 163766, 177503, 161730];
        uint16[8] memory counts = [uint16(114), 43, 50, 115, 39, 125, 125, 109];
        uint32[8] memory expected = [uint32(588553), 39271, 47425, 64228, 50199, 68949, 80043, 61332];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector18() public pure {
        uint32[8] memory p = [uint32(171271), 104653, 16564, 249357, 11926, 23797, 257981, 164451];
        uint16[8] memory counts = [uint16(20), 63, 48, 81, 56, 126, 17, 89];
        uint32[8] memory expected = [uint32(487895), 58433, 67993, 70850, 53936, 94453, 72472, 93968];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector19() public pure {
        uint32[8] memory p = [uint32(39065), 62274, 240198, 54280, 194843, 38382, 216764, 154194];
        uint16[8] memory counts = [uint16(87), 29, 122, 9, 8, 60, 125, 113];
        uint32[8] memory expected = [uint32(562464), 55826, 95946, 28815, 34495, 51463, 80160, 90831];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector20() public pure {
        uint32[8] memory p = [uint32(157968), 21350, 24516, 109428, 101996, 229726, 131059, 223957];
        uint16[8] memory counts = [uint16(31), 10, 62, 60, 65, 34, 16, 31];
        uint32[8] memory expected = [uint32(547845), 34175, 73626, 81967, 101592, 59474, 36988, 64333];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector21() public pure {
        uint32[8] memory p = [uint32(82931), 202468, 122007, 480, 131596, 251072, 105437, 104009];
        uint16[8] memory counts = [uint16(108), 53, 69, 99, 96, 60, 77, 127];
        uint32[8] memory expected = [uint32(545349), 42728, 72402, 87256, 69628, 51600, 52961, 78076];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector22() public pure {
        uint32[8] memory p = [uint32(17257), 205252, 30685, 28793, 213615, 306535, 5645, 192218];
        uint16[8] memory counts = [uint16(87), 104, 83, 107, 66, 115, 27, 89];
        uint32[8] memory expected = [uint32(480560), 103578, 92737, 63107, 73098, 67192, 38246, 81482];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector23() public pure {
        uint32[8] memory p = [uint32(249568), 195617, 52810, 143, 194180, 275093, 1842, 30747];
        uint16[8] memory counts = [uint16(69), 69, 13, 1, 106, 44, 106, 111];
        uint32[8] memory expected = [uint32(450625), 56918, 176916, 24801, 74497, 61610, 74651, 79982];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector24() public pure {
        uint32[8] memory p = [uint32(137623), 26772, 28135, 109682, 187197, 149114, 246725, 114752];
        uint16[8] memory counts = [uint16(49), 27, 59, 53, 55, 64, 41, 100];
        uint32[8] memory expected = [uint32(558736), 42842, 56387, 57743, 81225, 60965, 46509, 95593];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector25() public pure {
        uint32[8] memory p = [uint32(90309), 140398, 84914, 200463, 183739, 23924, 253565, 22688];
        uint16[8] memory counts = [uint16(48), 122, 17, 17, 2, 99, 97, 93];
        uint32[8] memory expected = [uint32(542136), 96102, 33301, 32024, 26647, 125128, 72430, 72232];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector26() public pure {
        uint32[8] memory p = [uint32(73671), 136846, 182924, 11081, 276906, 122614, 26272, 169686];
        uint16[8] memory counts = [uint16(111), 52, 121, 29, 48, 119, 12, 3];
        uint32[8] memory expected = [uint32(563889), 51286, 96411, 38086, 53039, 89770, 32143, 75376];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector27() public pure {
        uint32[8] memory p = [uint32(73167), 4005, 110997, 66593, 183818, 191407, 181999, 188014];
        uint16[8] memory counts = [uint16(106), 62, 53, 44, 91, 11, 66, 78];
        uint32[8] memory expected = [uint32(569610), 58766, 53811, 46158, 113123, 35066, 60608, 62858];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector28() public pure {
        uint32[8] memory p = [uint32(169300), 197801, 125426, 51722, 46396, 47934, 173316, 188105];
        uint16[8] memory counts = [uint16(45), 62, 54, 27, 79, 16, 121, 41];
        uint32[8] memory expected = [uint32(569740), 58639, 55174, 40108, 69475, 33346, 124921, 48597];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector29() public pure {
        uint32[8] memory p = [uint32(146204), 104376, 62587, 216362, 96819, 232132, 69447, 72073];
        uint16[8] memory counts = [uint16(22), 102, 43, 120, 75, 23, 117, 48];
        uint32[8] memory expected = [uint32(563519), 77517, 47415, 78812, 58173, 33920, 81777, 58867];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector30() public pure {
        uint32[8] memory p = [uint32(40056), 221247, 189869, 140946, 179113, 111484, 20282, 97003];
        uint16[8] memory counts = [uint16(6), 75, 86, 55, 92, 103, 56, 43];
        uint32[8] memory expected = [uint32(536137), 65673, 66963, 50451, 73164, 74532, 64424, 68656];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }

    function test_referenceVector31() public pure {
        uint32[8] memory p = [uint32(46916), 175013, 132072, 100988, 94388, 148120, 156818, 145685];
        uint16[8] memory counts = [uint16(10), 21, 40, 117, 127, 10, 127, 118];
        uint32[8] memory expected = [uint32(573547), 36033, 42204, 82849, 80799, 28429, 79248, 76891];
        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));
    }
}
