#!/usr/bin/env python3
"""Independent integer model: explicit 8x8 matrix, Python isqrt, sorted apportionment.

Python 3 standard library only. Regenerate committed fixtures with:
    python3 tools/model_reference.py
Tests use the resulting Solidity literals; Foundry never needs FFI/filesystem access.
"""
from math import isqrt
from pathlib import Path
from random import Random

SCALE = 1_000_000


def normalize(weights):
    total = sum(weights)
    assert total > 0
    divisions = [divmod(w * SCALE, total) for w in weights]
    result = [q for q, _ in divisions]
    order = sorted(range(8), key=lambda i: (-divisions[i][1], i))
    for i in order[:SCALE - sum(result)]:
        result[i] += 1
    assert sum(result) == SCALE
    return result


def transition(p, counts):
    assert sum(p) == SCALE and min(p) >= 0
    assert min(counts) >= 0 and sum(counts) <= 1024
    amplitudes = [isqrt(x * SCALE) for x in p]
    transformed = [sum((-1) ** ((i & j).bit_count()) * amplitudes[j]
                       for j in range(8)) for i in range(8)]
    coherent = normalize([a * a for a in transformed])
    mixed = normalize([3 * x + SCALE // 8 for x in coherent])
    n = sum(counts)
    return mixed if n == 0 else normalize([3 * x * n + c * SCALE for x, c in zip(mixed, counts)])


def solidity_array(values, kind):
    return f"[{kind}({values[0]}), " + ", ".join(map(str, values[1:])) + "]"


def main():
    rng = Random(0x514F4253)
    cases = [([125000] * 8, [0] * 8), ([125000] * 8, [0] * 7 + [1]),
             ([999993] + [1] * 7, [1024] + [0] * 7),
             ([1, 2, 3, 4, 5, 6, 7, 999972], [128] * 8)]
    for state in range(8):
        p = [0] * 8
        p[state] = SCALE
        cases.append((p, [0] * 8))
    for _ in range(20):
        p = normalize([rng.randrange(1, SCALE) for _ in range(8)])
        counts = [rng.randrange(129) for _ in range(8)]
        cases.append((p, counts))
    lines = ["// SPDX-License-Identifier: MIT", "pragma solidity 0.8.26;", "",
             '// Generated by tools/model_reference.py; checked-in oracle vectors.',
             'import {Test} from "forge-std/Test.sol";',
             'import {QuantumModel} from "../src/QuantumModel.sol";',
             '', 'contract QuantumVectorsTest is Test {']
    for index, (p, counts) in enumerate(cases):
        lines += [f"    function test_referenceVector{index:02d}() public pure {{",
                  f"        uint32[8] memory p = {solidity_array(p, 'uint32')};",
                  f"        uint16[8] memory counts = {solidity_array(counts, 'uint16')};",
                  f"        uint32[8] memory expected = {solidity_array(transition(p, counts), 'uint32')};",
                  "        assertEq(abi.encode(QuantumModel.transition(p, counts)), abi.encode(expected));",
                  "    }"]
    lines += ["}", ""]
    target = Path(__file__).resolve().parent.parent / "test/QuantumVectors.t.sol"
    target.write_text("\n".join(lines))
    print(f"Wrote {len(cases)} differential vectors to {target.name}")


if __name__ == "__main__":
    main()
